# Generated by Django 3.0.6 on 2020-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100, unique=True)),
                ('repo_description', models.CharField(max_length=100)),
                ('rep_lang', models.CharField(max_length=100)),
                ('forks', models.CharField(max_length=250)),
                ('created_on', models.DateField()),
                ('collaborators', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
