# Generated by Django 3.0.6 on 2020-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_github', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Repository',
        ),
    ]
