# Generated by Django 3.0.6 on 2020-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_github', '0002_auto_20200521_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='forks',
            field=models.IntegerField(),
        ),
    ]
